import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ChatLayout from '@/layouts/ChatLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
          <ChatLayout>
            {children}
          </ChatLayout>
      </body>
    </html>
  )
}